version: "3"

services:
  postgres:
    build:
      context: docker/postgres_db/.docker-containers/postgres
    restart: "on-failure"
#    expose:
#      - 5432
    env_file:
      - docker/postgres_db/.docker-env/dev/postgres.env
    environment:
      - POSTGRES_DB_USER=docker
    ports:
      - "5433:5432"
    ulimits:
      nproc: 128000
      nofile:
        soft: 50000
        hard: 120000
    networks:
      - django-project


volumes:
  postgres:


networks:
  django-project:
