# Generated by Django 5.0 on 2023-12-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[(
                """alter table core_article
                    drop constraint core_article_reporter_id_4e3ac626_fk_core_reporter_id,
                    add constraint core_article_reporter
                        foreign key (reporter_id)
                        references core_reporter
                    on delete CASCADE;"""
            )],
            reverse_sql=None
        )
    ]
